"""Negative controls for the evidence source-state binding."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[1] / "tools"


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )


def _fixture_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    demo = repo / "demo-rate-limiter"
    for directory in (
        repo / ".github/workflows",
        demo / "examples",
        demo / "src/ratelimiter",
        demo / "tests",
        demo / "tools",
    ):
        directory.mkdir(parents=True)

    (repo / ".gitignore").write_text(
        "*.egg-info/\n__pycache__/\n*.pyc\n.coverage\ncoverage.xml\n",
        encoding="utf-8",
    )
    (repo / ".github/workflows/gauntlet.yml").write_text("name: test\n")
    (repo / "README.md").write_text("metadata only\n")
    (demo / "examples/demo.py").write_text("print('demo')\n")
    (demo / "pyproject.toml").write_text("[project]\nname = 'fixture'\n")
    (demo / "requirements-dev.txt").write_text("pytest==0\n")
    (demo / "spec.md").write_text("# fixture spec\n")
    (demo / "src/ratelimiter/__init__.py").write_text("VALUE = 1\n")
    (demo / "tests/test_fixture.py").write_text("def test_fixture(): pass\n")
    shutil.copy2(TOOLS / "source_state.sh", demo / "tools/source_state.sh")
    implementation = TOOLS / "source_state.py"
    if implementation.exists():
        shutil.copy2(implementation, demo / "tools/source_state.py")

    _git(repo, "init", "-q")
    _git(repo, "config", "user.name", "Source State Test")
    _git(repo, "config", "user.email", "source-state@example.invalid")
    _git(repo, "add", ".")
    _git(repo, "commit", "-qm", "fixture")
    return repo


def _run_state(
    repo: Path, *, cwd: Path | None = None
) -> subprocess.CompletedProcess[str]:
    script = repo / "demo-rate-limiter/tools/source_state.sh"
    return subprocess.run(
        [str(script)],
        cwd=cwd or repo,
        check=False,
        capture_output=True,
        text=True,
    )


def _state(result: subprocess.CompletedProcess[str]) -> dict[str, str]:
    assert result.returncode == 0, result.stderr
    state = dict(line.split(":", 1) for line in result.stdout.splitlines())
    return {key.strip(): value.strip() for key, value in state.items()}


def test_ignored_build_products_do_not_change_tree_hash(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    before = _state(_run_state(repo))
    generated = repo / "demo-rate-limiter/src/ratelimiter.egg-info"
    generated.mkdir()
    (generated / "PKG-INFO").write_text("generated metadata\n")
    cache = repo / "demo-rate-limiter/tests/__pycache__"
    cache.mkdir()
    (cache / "test_fixture.pyc").write_bytes(b"generated bytecode")

    after = _state(_run_state(repo))

    assert after["tree"] == before["tree"]


def test_dirty_tracked_source_fails_closed(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    source = repo / "demo-rate-limiter/src/ratelimiter/__init__.py"
    source.write_text("VALUE = 2\n")

    result = _run_state(repo)

    assert result.returncode != 0
    assert "dirty" in result.stderr.lower()

    _git(repo, "add", "demo-rate-limiter/src/ratelimiter/__init__.py")
    staged_result = _run_state(repo)
    assert staged_result.returncode != 0
    assert "dirty" in staged_result.stderr.lower()


def test_nonignored_untracked_source_fails_closed(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    (repo / "demo-rate-limiter/src/ratelimiter/new.py").write_text("VALUE = 2\n")

    result = _run_state(repo)

    assert result.returncode != 0
    assert "untracked" in result.stderr.lower()


def test_missing_manifest_input_fails_closed(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    (repo / "demo-rate-limiter/pyproject.toml").unlink()

    result = _run_state(repo)

    assert result.returncode != 0


def test_clean_archive_matches_git_from_any_directory(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    git_state = _state(_run_state(repo, cwd=tmp_path))
    clone = tmp_path / "clone"
    subprocess.run(
        ["git", "clone", "-q", str(repo), str(clone)],
        check=True,
        capture_output=True,
        text=True,
    )
    clone_state = _state(_run_state(clone, cwd=clone / "demo-rate-limiter/tests"))
    archive = tmp_path / "archive"
    for relative in _git(repo, "ls-files").stdout.splitlines():
        source = repo / relative
        destination = archive / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    archive_state = _state(_run_state(archive, cwd=archive / "demo-rate-limiter/src"))

    assert clone_state["tree"] == git_state["tree"] == archive_state["tree"]
    assert archive_state["head"] == "(no git)"
    assert archive_state["source commit"] == "(no git)"


def test_evidence_only_commit_preserves_source_binding(tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    before = _state(_run_state(repo))
    (repo / "README.md").write_text("new evidence prose\n")
    _git(repo, "add", "README.md")
    _git(repo, "commit", "-qm", "evidence only")

    after = _state(_run_state(repo))

    assert after["head"] != before["head"]
    assert after["source commit"] == before["source commit"]
    assert after["tree"] == before["tree"]
